# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0003_auto_20171025_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='receiver',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='user_dashboard.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to='user_dashboard.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_comment', to='user_dashboard.Message'),
        ),
    ]
