# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0008_comment_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='receiver',
        ),
    ]
